from langgraph.graph import StateGraph, END
from typing import TypedDict, Any
from langchain_core.messages import AnyMessage, SystemMessage, HumanMessage, ToolMessage, AIMessage
from langchain_openai import ChatOpenAI
import os
from dotenv import load_dotenv, find_dotenv 
from langgraph.checkpoint.sqlite import SqliteSaver
from pydantic import BaseModel
import pandas as pd
from visualisations import build_chart

load_dotenv(find_dotenv())

class AgentState(TypedDict):
    question: str
    sql: str
    data: list[dict]
    
    chart_specs: list[dict]
    figures: list[Any]
    descriptions: list[str]

class ChartSpecs(BaseModel):
    type: str
    x: str
    y: str
    title: str

class ChartList(BaseModel):
    charts: list[ChartSpecs]

class Analytics_result(TypedDict):
    title: str
    figure: Any
    description: str


# === PROMPTS FOR THE LLM NODES ===

#Planner
planner_prompt = """You are an analytics expert. 
You take the user question, the sql code and the data generated by the sql. \
You have to intelligently deduce 4 graphs based on this data which would be most helpful. \
Do not write python. Respond in JSON.
"""

#Generating insights
generate_insight_prompt = """You are a bussiness analyst.
Look at the char given and generate a concise sentence explaining the main takeaway. \
Do not invent facts.
Only use the data given.
"""

# === FUNCTIONS FOR GRAPH NODES ===

#Planner node
def planner_node(state: AgentState):
    UserMessage = HumanMessage(content=f"User Question: {state['question']}\n\nSQL geenrated: {state['sql']}\n\nData generated: {state['data']}")
    messages = (
        SystemMessage(content=planner_prompt),
        UserMessage
    )
    response = model.with_structured_output(ChartList).invoke(messages)
    return {"chart_specs": response.charts}

#Graph generator node
def graph_generator_node(state: AgentState):
    df = pd.DataFrame(state['data'])
    figures = []
    for spec in state['chart_specs']:
        fig = build_chart(df, spec)
        figures.append(fig)
    return {"figures": figures}

#Generate Insights node
def generate_insight_node(state: AgentState):
    descriptions = []
    for fig in state['figures']:
        messages = (
            SystemMessage(content=generate_insight_prompt),
            HumanMessage(content=fig)
        )
        response = model.invoke(messages)
        descriptions.append(response.content)

# === BUILDING THE GRAPH ===
builder = StateGraph(AgentState)
builder.add_node("Planner", planner_node)
builder.add_node("Graph_generator", graph_generator_node)
builder.add_node("Generate_Insights", generate_insight_node)
builder.set_entry_point("Planner")
builder.add_edge("Planner", "Graph_generator")
builder.add_edge("Graph_generator", "Generate_Insights")
builder.add_edge("Generate_Insights", END)

model = ChatOpenAI(model="gpt-4o-mini", temperature=0)

def run_analytics(result: dict) -> list[dict]:

    with SqliteSaver.from_conn_string(":memory:") as memory:

        graph = builder.compile(checkpointer=memory)
        thread = {"configurable": {"thread_id": "1"}}
        state = {
            "question": result['user'],
            "sql": result['sql'],
            "data": result['data'],
            "chart_specs": [],
            "figures": [],
            "descriptions": []
        }
        final_state = graph.invoke(state, thread)
        charts = final_state['chart_specs']
        analytics: list[Analytics_result] = []
        for c, fig, desc in zip(charts, final_state['figures'], final_state['descriptions']):
            analytics.append({
                "title": c.title,
                "figure": fig,
                "description": desc
            })
        return analytics


