from langgraph.graph import StateGraph, END
from typing import TypedDict, Any
from langchain_core.messages import AnyMessage, SystemMessage, HumanMessage, ToolMessage, AIMessage
from langchain_openai import ChatOpenAI
import os
from dotenv import load_dotenv, find_dotenv 
from langgraph.checkpoint.sqlite import SqliteSaver
from pydantic import BaseModel
import pandas as pd

load_dotenv(find_dotenv())

model = "gpt-4o-mini"

class AgentState(TypedDict):
    question: str
    sql: str
    data: list[dict]
    
    chart_specs: list[dict]
    figures: list[Any]
    descriptions: list[str]

class ChartSpecs(BaseModel):
    type: str
    x: str
    y: str
    title: str

class ChartList(BaseModel):
    charts: list[ChartSpecs]

# === PROMPTS FOR THE LLM NODES ===

#Planner
planner_prompt = """You are an analytics expert. 
You take the user question, the sql code and the data generated by the sql. \
You have to intelligently deduce 4 graphs based on this data which would be most helpful. \
Do not write python. Respond in the provided structured output.
"""

#Evaluate Figures
evaluating_figures_prompt = """
"""

# === FUNCTIONS FOR GRAPH NODES ===

#Planner node
def planner_node(state: AgentState):
    UserMessage = HumanMessage(content=f"User Question: {state['question']}\n\nSQL geenrated: {state['sql']}\n\nData generated: {state['data']}")
    messages = (
        SystemMessage(content=planner_prompt),
        UserMessage
    )
    response = model.with_structured_output(ChartList).invoke(messages)
    return {"chart_specs": response.charts}

#Graph generator node
def graph_generator(state: AgentState):
    df = pd.DataFrame(state['data'])